(defvar rl-dir-autogen
  (file-name-as-directory (expand-file-name "autogen" user-emacs-directory))
  "Directory for files that generated by Emacs.")


(defun rl-init-module-file ()
  "Initialize file module."
  (rl--set-up-autogens)
  (rl--set-up-autosave)
  (rl--set-up-backup)
  (rl--set-up-dired)
  (rl--set-up-recentf)
  (rl--set-up-open))


(defun rl-get-current-path-dwim ()
  "Get file path from current buffer, and try to be smart with it."
  (cond
   ;; When in dired mode, try get path under the cursor, otherwise return the current directory
   ((equal major-mode `dired-mode)
    (let ((path (ignore-errors (dired-get-file-for-visit))))
      (if path path default-directory)))
   ;; Return file name of current buffer
   (t buffer-file-name)))


;; http://emacsredux.com/blog/2013/03/27/open-file-in-external-program/
(defun rl-open-with (arg)
  "Open file in default external program.
 With a prefix ARG always prompt for command to use"
  (interactive "P")
  (let ((path (rl-get-current-path-dwim)))
    (when path (shell-command
                (concat
                 (cond
                  ((and (not arg) (eq system-type 'darwin)) "open")
                  ((and (not arg) (member system-type '(gnu gnu/linux gnu/kfreebsd))) "xdg-open")
                  (t (read-shell-command "Open current file with: ")))
                 " "
                 (shell-quote-argument path))))))


(defun rl-sub-dir-autogen (sub-dir-name)
  "Create a directory under `rl-dir-autogen' and return the path."
  (let ((sub-dir-path (expand-file-name sub-dir-name rl-dir-autogen)))
    (make-directory sub-dir-path t)
    (file-name-as-directory sub-dir-path)))


(defun rl--set-up-autogens ()
  "Set up files that can be generated by emacs packages."
  (unless (file-exists-p rl-dir-autogen)
    (make-directory rl-dir-autogen t)))


(defun rl--set-up-backup ()
  "Set up emacs backup behavior."
  (setq backup-directory-alist `((".*" . ,(rl-sub-dir-autogen "backup"))))
  (setq-default backup-by-copying t))


(defun rl--set-up-autosave ()
  "Set up emacs auto save behavior."
  (setq auto-save-file-name-transforms `((".*" ,(rl-sub-dir-autogen "save") t)))
  (setq auto-save-list-file-prefix nil))


(defun rl--set-up-dired ()
  "Set up Dired."
  (use-package dired
    :config
    (when (string-equal system-type "darwin")
      (setq insert-directory-program "/usr/local/bin/gls"))
    (setq dired-listing-switches "-aBhl  --group-directories-first")
    (setq dired-dwim-target t)))


(defun rl--set-up-recentf ()
  "Set up Recentf."
  (use-package recentf
    :config
    (setq recentf-save-file (expand-file-name "recentf" rl-dir-autogen))
    (setq recentf-auto-cleanup 'never) ; to avoid accidentally remote file access
    (setq recentf-max-saved-items 100)
    (setq recentf-max-menu-items 15)
    (run-at-time nil (* 5 60) 'recentf-save-list) ; save recent files every 5 mins
    (recentf-mode 1)))


(defun rl--set-up-open ()
  (bind-key "C-c o" 'rl-open-with))



(provide 'module-file)
