(defvar rl/dir-autogen
  (file-name-as-directory (expand-file-name "autogen" user-emacs-directory))
  "Directory for files that generated by Emacs.")


(defun rl/initialize-module-file ()
  "Initialize file module."
  (rl--set-up-autogens)
  (rl--set-up-autosave)
  (rl--set-up-backup)
  (rl--set-up-dired)
  (rl--set-up-recentf))


(defun rl/recentf-ido-find-file ()
  "Find a recent file using Ido."
  (interactive)
  (let ((file (ido-completing-read "Choose recent file: " recentf-list nil t)))
    (when file
      (find-file file))))


(defun rl/sub-dir-autogen (sub-dir-name)
  "Create a directory under `rl/dir-autogen' and return the path."
  (let ((sub-dir-path (expand-file-name sub-dir-name rl/dir-autogen)))
    (make-directory sub-dir-path t)
    (file-name-as-directory sub-dir-path)))



(defun rl--set-up-autogens ()
  "Set up files that can be generated by emacs packages."
  (unless (file-exists-p rl/dir-autogen)
    (make-directory rl/dir-autogen t))
  (setq recentf-save-file (expand-file-name "recentf" rl/dir-autogen)))


(defun rl--set-up-backup ()
  "Set up emacs backup behavior."
  (setq backup-directory-alist `((".*" . ,(rl/sub-dir-autogen "backup"))))
  (setq-default backup-by-copying t))


(defun rl--set-up-autosave ()
  "Set up emacs auto save behavior."
  (setq auto-save-file-name-transforms `((".*" ,(rl/sub-dir-autogen "save") t)))
  (setq auto-save-list-file-prefix nil))


(defun rl--set-up-dired ()
  "Set up Dired."
  (use-package dired
    :config
    (when (string-equal system-type "darwin")
      (setq insert-directory-program "/usr/local/bin/gls"))
    (setq dired-listing-switches "-aBhl  --group-directories-first")
    (setq dired-dwim-target t)))


(defun rl--set-up-recentf ()
  "Set up Recentf."
  (use-package recentf
    :config
    (setq recentf-auto-cleanup 'never) ; to avoid accidentally remote file access
    (setq recentf-max-saved-items 100)
    (setq recentf-max-menu-items 15)
    (run-at-time nil (* 5 60) 'recentf-save-list) ; save recent files every 5 mins
    (recentf-mode 1)
    (bind-key "C-x C-r" 'rl/recentf-ido-find-file)))



(provide 'module-file)
