#+TITLE: Rangi's Emacs configuration

This is my personal Emacs configuration.

** Rewrite
The latest rewrite is in 2025, based on Emacs 30.1.

In this rewrite I focus on a few things:
1. Keep it simple: Reduce the amount of opinioned customizations as reasonably as I can, according to my own needs and opinions. Use built-in features when it's good enough, only rely on 3rd-party packages when it is necessary. This also encourage me to learn more about Emacs.
2. Keep it fast: Keep it simple helps a lot. I also intentionally add very little performance tweaks this time and dropped most old one I had. Will add more if I actually need it.
3. Keep it safe: Again, keep it simple helps a lot. Now I don't need many packages, only those in Elpa(GNU/NonGNU) repositories are installed via package.el, others are installed manually. All packages are updated manually when I need to, instead of constantly update codes from dozens of repositories without me knowing.

** Emacs
I'm using @drkp maintained Emacs on MacPorts.
https://ports.macports.org/port/emacs-app/

** External Dependencies
1. Most packages that is not included in `site-lisp` are installed from GNU / NonGNU ELPA.
2. There are a few external command line used:
  - `rust-analyzer` for running eglot for Rust
  - `multimarkdown` for markdown mode
  - `aspell` for `flyspell`
