#+TITLE: Rangi's Emacs configuration

This is my personal Emacs configuration.

** Principles

The current version of configuration was started in 2025, based on Emacs 30.1.

I focused on a few things in this version:

1. Simple
2. Fast
3. Safe
4. Reasonable

I reduced the amount of opinionated customizations I had. Use built-in package as much as possible, only use 3rd party packages when there are significant advantages, and when there is no other choice. This encourages me to learn more Emacs's built-in features.

I enabled native compilation, so packages are compiled natively to have better performance. Lazy loading packages as much as possible also helps start up time, currently this configuration only need 0.5 seconds to start according to `use-package-report` once the complication is done.

Security is a major concerns in this rewrite, several changes are made to address this:

1. Packages are only installed automatically using package.el via GNU and NonGNU ELPA.
2. Other packages are manually copied to `site-lisp` directory and loaded from there.
3. No auto update, only manually update when I feel like it or out of necessity, which is not often.
4. Packages on ELPAs are updated using `package.el`, the rest of them are manually reviewed before replacing exist one.

Last, be reasonable, this tool is to used to serve me, not the other way around, or at least not all the time.


** Emacs
I'm using @drkp maintained Emacs on MacPorts.
https://ports.macports.org/port/emacs-app/


** External Dependencies
There are a few external command line used (programming languages related are not listed):
- `multimarkdown`: for Markdown converting to format.
- `gls` from `coreutils`: for Dired for directory first sorting order
- `enchant2`: for Jinx for faster spell checking
