(defvar rangi/gen-dir (file-name-as-directory (expand-file-name ".gen" user-emacs-directory))
  "Directory to put files that generated by Emacs")

(defvar rangi/startup-file "/ramsey/Dropbox/org/personal/main.org"
  "File to open when emacs is started")

(defvar rangi/theme 'afternoon
  "Default theme")
(custom-set-variables '(monokai-use-variable-pitch nil))

(require 'local-variables nil t)

(provide 'variables)
